### ISSUE TITLE
Error trying to compile

### ISSUE THREAD

**Issue by willianpc** [wasdk/wasdk#2]
Hi, first of all, very good job with the Fiddle! It works very smoothly!
I am now trying to use the API locally, I installed it with npm install, but when I try to build a c file to wasm I am getting some errors, maybe you have some ideas.
I had to add sudo on Mac after installing wasdk with `npm install -g`

```shell
$ sudo wasdk ez fib.c -o fib.js
WARNING:root:Assigning a non-existent settings attribute "BINARYEN_IMPRECISE"
WARNING:root: - did you mean one of BINARYEN_PASSES, BINARYEN_METHOD, BINARYEN_MEM_MAX?
WARNING:root: - perhaps a typo in emcc's  -s X=Y  notation?
WARNING:root: - (see src/settings.js for valid values)
Unknown option '--emit-jsified-potential-traps'
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/wasdk/bin/emscripten/emcc", line 13, in <module>
    emcc.run()
  File "/usr/local/lib/node_modules/wasdk/bin/emscripten/emcc.py", line 2169, in run
    subprocess.check_call(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/lib/node_modules/wasdk/bin/binaryen/bin/asm2wasm', '/Users/wcarvalho/projects/webassembly/fib.asm.js', '--total-memory=16777216', '--emit-jsified-potential-traps', '-O3', '--table-max=-1', '--mem-max=-1', '-o', '/Users/wcarvalho/projects/webassembly/fib.wasm']' returned non-zero exit status 1
/usr/local/lib/node_modules/wasdk/dist/wasdk.js:317
        shared_1.fail("Compilation error: " + res.error.toString());
                                                       ^

TypeError: Cannot read property 'toString' of undefined
    at ezCompile (/usr/local/lib/node_modules/wasdk/dist/wasdk.js:317:56)
    at Object.<anonymous> (/usr/local/lib/node_modules/wasdk/dist/wasdk.js:53:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```

Cheers!

**Comment by yurydelendik** [comment]
> Unknown option '--emit-jsified-potential-traps'

Looks like binaryen and emsdk out of sync

**Comment by willianpc** [comment]
Thanks for the quick reply. What can I do to sync them? I noticed I might have skipped a step to install SDK in the section `manage sdk`. Then I did that and got a success installation:

```shell
$ sudo wasdk sdk --install
Password:
Installing Emscripten
File already downloaded, skipping.
Unpacking ✔
File already downloaded, skipping.
Unpacking ✔
Installing LLVM
File already downloaded, skipping.
Unpacking ✔
Installing Binaryen
File already downloaded, skipping.
Unpacking ✔
Installing Spidermonkey
File already downloaded, skipping.
Unpacking ✔
```

Then, I tried again.. The first run some stuff is cached, and there are some more errors about version of Emscripten. Can you please take a look? The installation happened through `npm install`, so I didn't change any version or anything.

```shell
$ sudo wasdk ez fib.c -o fib.js
INFO:root:generating system asset: is_vanilla.txt... (this will be cached in "/Users/wcarvalho/.emscripten_cache/is_vanilla.txt" for subsequent builds)
INFO:root: - ok
WARNING:root:(Emscripten: settings file has changed, clearing cache)
WARNING:root:LLVM version appears incorrect (seeing "3.9", expected "4.0")
ERROR:root:Emscripten, llvm and clang repo versions do not match, this is dangerous (1.37.8, 1.37.5, 1.37.5)
ERROR:root:Make sure to use the same branch in each repo, and to be up-to-date on each. See http://kripken.github.io/emscripten-site/docs/building_from_source/LLVM-Backend.html
INFO:root:(Emscripten: Running sanity checks)
WARNING:root:Assigning a non-existent settings attribute "BINARYEN_IMPRECISE"
WARNING:root: - did you mean one of BINARYEN_PASSES, BINARYEN_METHOD, BINARYEN_MEM_MAX?
WARNING:root: - perhaps a typo in emcc's  -s X=Y  notation?
WARNING:root: - (see src/settings.js for valid values)
Unknown option '--emit-jsified-potential-traps'
```
And from this point on, the same errors as I shared previously :)

Thanks again!
Willian

**Comment by WorldThirteen** [comment]
@chambs, try to compile binaryen from https://github.com/WebAssembly/binaryen, and copy `binaryen/bin` directory content to `wasdk/bin/binaryen/bin`. This helped me.

**Comment by yurydelendik** [comment]
I updated the builds at wasdk/wasdk-platform-tools for mac and going to produce builds for other platforms soon (currently there are some issues with https://wasm-stat.us/)

**Comment by yurydelendik** [comment]
The issue shall be fixed for now by https://github.com/wasdk/wasdk-platform-tools/commit/41e53990dbaa8e6eda077194534a6256bd02231d

**Comment by willianpc** [comment]
Thanks @yurydelendik 
I will take a look.

Cheers
